# !/bin/bash
# Helper testing script for indexer.c 
# 
# Canonically sorts indexes generated by
# indexer
# 
# Stdout, stderr, and exit status
# will be compared to sorted versions
# of indexes given in tse-output.
#
# Author: Sabrina Jain
# Date: February 16, 2020
# usage: bash sorting_index.sh

#Sorting letters index (depth 0)
gawk -f indexsort.awk ../data/indexes/letters-myindex-0

#Sorting letters index (depth 1)
gawk -f indexsort.awk ../data/indexes/letters-myindex-1

#Sorting letters index (depth 2)
gawk -f indexsort.awk ../data/indexes/letters-myindex-2

#Sorting letters index (depth 3)
gawk -f indexsort.awk ../data/indexes/letters-myindex-3

#Sorting letters index (depth 4)
gawk -f indexsort.awk ../data/indexes/letters-myindex-4

#Sorting letters index (depth 5)
gawk -f indexsort.awk ../data/indexes/letters-myindex-5

#Sorting letters index (depth 6)
gawk -f indexsort.awk ../data/indexes/letters-myindex-6

#Sorting book scrape index (depth 0)
gawk -f indexsort.awk ../data/indexes/toscrape-myindex-0

#Sorting book scrape index (depth 1)
gawk -f indexsort.awk ../data/indexes/toscrape-myindex-1

#Sorting book scrape index (depth 2)
gawk -f indexsort.awk ../data/indexes/toscrape-myindex-2

#Sorting wikipedia index (depth 0)
gawk -f indexsort.awk ../data/indexes/wikipedia-myindex-0

#Sorting wikipedia index (depth 1)
gawk -f indexsort.awk ../data/indexes/wikipedia-myindex-1

#Sorting wikipedia index (depth 2)
gawk -f indexsort.awk ../data/indexes/wikipedia-myindex-2

exit 0