# Makefile for 'crawler'

CC = gcc
CFLAGS = -Wall -pedantic -std=c11 -ggdb $(TESTING) -I../libcs50  -I../common # -DTEST
OBJS = crawler.o ../libcs50/memory.o ../libcs50/hashtable.o ../libcs50/bag.o  ../libcs50/webpage.o ../libcs50/jhash.o ../libcs50/set.o ../libcs50/file.o ../common/pagedir.o
LIBS = -lm
PROG = crawler
TEST = testing.sh

TESTING=-DMEMTEST

.PHONY: test clean 


# executable depends on object files
$(PROG): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) $(LIBS) -o $(PROG)

# object files depend on include files
crawler.o: ../libcs50/memory.h ../libcs50/hashtable.h ../libcs50/bag.h ../libcs50/webpage.h ../libcs50/set.h ../libcs50/jhash.h ../libcs50/file.h ../common/pagedir.h


test: $(TEST) 
	bash -v $(TEST)


clean:
	rm -f $(PROG)
	rm -f *~ *.o
	rm -rf *.dSYM
	rm -rf *~
	rm -rf .crawler*

